### PR TITLE
Use Pathlib for example notebook

### PR DESCRIPTION
**Pull request by NicolasCARPi**
Hello,

So there are still a few things that bother me when working with this codebase:

* you're using old school strings as path but you know about Pathlib, so I would recommend that you ALWAYS use Pathlib everywhere. This change is an example of that. So instead of having:

~~~python
Name = os.path.basename(os.path.splitext(ImageName)[0])
~~~

You can use:

~~~python
Name = ImageName.stem
~~~

(in fact here it could directly be passed in the function call, no need to create the variable Name)

Much better, no? And [here](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module) you'll find the correspondence.

Also in the example I renamed the variables, it is important to have meaningful names (for instance `Name` is not meaningful enough). If it's a Path, call it SomethingPath so we know what we're dealing with.

* You are not using typing, and it really helps to do it. So when you move to using Paths instead of plain string, also add typing to the function signature so we know what it expects. Here in this example I've used `str(something)` but of course the correct way is for the function itself to accept Paths and not string like it's 1998 :p 

* Don't forget to run `black --skip-string-normalization /path/to/file` to remove all the whitespaces you're adding:

2021-05-18-124255_626x189_scrot

You can also configure your text editor to prevent this (and/or git, see git-stripspace).

* you're using PascalCase for your variables, probably because you're coming from Matlab world, it's not an issue, it's just not what one would expect in a python codebase. We can also find camelCase and snake_case in the codebase. I think it's important to be consistent in naming things, and follow [standards](https://www.python.org/dev/peps/pep-0008/) so other developers can drop-in easily. You can also use a linter like `pylint`. And you can have a pre-commit hook to lint/format the code. It may seem like a minor detail, but it really is not. Consistency in a codebase is paramount.

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Other things that are bothering:

* the `examples/output` folder contains git tracked data, but the examples will modify this, it creates noise in the diff (and the notebooks are already creating a lot of noise!!! (I don't like notebooks)). An output folder must not exist, be created if needed, and only contain git ignored data. It's not good to mix things like it is now.
* There are still some ipynb_checkpoints folders that are tracked for some reason.

**Comment by NicolasCARPi** [comment]
This PR is a good example of the highly unreadable git diff produced when working with notebooks....

**Comment by kapoorlab** [comment]
Thanks Nicolas, I also prefer the snake_case and in my other repositories I have started making this change. You do not like notebooks? at all? What alternative UI you prefer for the end users? I will work on not having the output folder and on removing the .ipynb checkpoints. I use pathlib to create paths but the strings usage was inherited from old way of doing things, thanks for pointing this and other things out. I will work on them ASAP now.

**Comment by NicolasCARPi** [comment]
> You do not like notebooks? at all?

While I admit they have their use, I never use them as they have several major drawbacks (to me):

- do not play well with git
- need to use the mouse
- editing code inside it means I can't use my normal editor
- state of the program depends on which cells you clicked
- it's for kids or very short programs/demo

But that's because I'm kinda old school, with all done in the terminal, vim is my only editor, I don't use a mouse nor a gui for most of my tasks. So using the browser to do code editing is really not something I consider "good". I don't mean to say it's bad to use notebooks, it's just that I don't like them and prefer a simple python script instead! ;)

> I use pathlib to create paths but the strings usage was inherited from old way of doing things

Yep, that's called "technical debt" ;) We all have that in our projects ^^ 

---


I'll probably continue hacking on this project today or tomorrow. My next step will be to make a proper console script that we can call like if it was a binary. And later on, once this is done, look into Docker so it can easily be used anywhere Docker exists.

**Pull request merged**
